<footer>CSC 174: Advanced Front-End Web Design and Development</footer>
	<nav class="menu">
		<ul>
			<li><a href="index.php">Home</a></li>
			<li><a href="early_days.php">Early Days</a></li>
			<li><a href="sports_background.php">Sports Background</a></li>
			<li><a href="academic_interests.php">Academic Interests</a></li>
			<li><a href="courses.php">Courses</a></li>
		</ul>
	</nav>
	<script src="//ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="js/menu-highlighter.js"></script>
</body>
</body>
</html>